version: "3.8"

services:
  db:
    image: postgres:15-alpine
    container_name: abacatepay_db
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=abacatepay_user
      - POSTGRES_PASSWORD=abacatepay_password
      - POSTGRES_DB=abacatepay_db
    ports:
      - "5432:5432"
    restart: unless-stopped

  api:
    build: .
    container_name: abacatepay_api
    command: gunicorn -k uvicorn.workers.UvicornWorker --conf gunicorn_conf.py src.main:app
    env_file:
      - .env
    depends_on:
      - db
    restart: unless-stopped
    expose:
      - 8000

  nginx:
    image: nginx:latest
    container_name: abacatepay_nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - api
    restart: unless-stopped

volumes:
  postgres_data:
